In [1]:
!pip install numpy pandas matplotlib

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
#escalar: temperatura
#dimension 0
escalar = np.array(42)
print(type(escalar))
print(escalar)

<class 'numpy.ndarray'>
42


In [4]:
#vector: lista
#dimension: 1
vector = np.array([30,12,15,56,48,59,16,46])
print(vector)

[30 12 15 56 48 59 16 46]


In [5]:
#matriz: permite el procesamiento de imagenes...
#dimension: 2
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
#tensor: pemite el procesameinto de varias imagenes ...
#dimension: 3 a mas
tensor = np.array([[1,2],[3,2],[7,8]])
print(tensor)

[[1 2]
 [3 2]
 [7 8]]


In [7]:
#creacion de matrices de forma secuencial
array_arange = np.arange(10)
print(array_arange)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
#matriz identidad
eye_matrix = np.eye(6)
print(eye_matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [10]:
#matriz diagonal
diag = np.diag([1,2,3,4,5,6])
print(diag)

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


In [11]:
#matrix aleatoria
random = np.random.random((2,3))
print(random)

[[0.43699398 0.583852   0.01761233]
 [0.52966298 0.03166537 0.23183872]]


# ARRAY

Arrays en NumPy son herramientas versátiles utilizadas para representar imágenes, sonidos y otros tipos de datos científicos.

Arrays en NumPy son estructuras de datos multidimensionales que permiten:

* Almacenar datos homogéneos (todos del mismo tipo).
* Tener múltiples dimensiones (vectores, matrices, etc.).
* Realizar operaciones matemáticas de manera eficiente.
* Acceder y modificar datos fácilmente con indexación y slicing.

In [13]:
array = np.array([[1,2,3],[4,5,6]])
print(array.ndim) #indica la dimension de la matriz
print(array.shape) #indica los indices
print(array.dtype) # indica el tipo de dato del array

2
(2, 3)
int64


In [16]:
#suma
tensor = np.array([[1,2],[3,2],[7,8]])
suma = np.sum(tensor)
print(suma)

23


In [17]:
#media
mean = np.mean(array)
print(mean)

3.5


In [18]:
#desviacion estandar
std = np.std(tensor)
print(std)

2.6718699236468995


In [19]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

suma = A + B
print("Suma de matrices:\n", suma)

Suma de matrices:
 [[ 6  8]
 [10 12]]


In [20]:
producto = np.dot(A, B)
print("Producto de matrices:\n", producto)


Producto de matrices:
 [[19 22]
 [43 50]]


In [23]:
determinante = np.linalg.det(A)
print("Determinante de A:", determinante)

Determinante de A: -2.0000000000000004


In [22]:
inversa = np.linalg.inv(A)
print("Inversa de A:\n", inversa)

Inversa de A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [24]:
valores_propios, vectores_propios = np.linalg.eig(A)
print("Valores propios de A:\n", valores_propios)
print("Vectores propios de A:\n", vectores_propios)

Valores propios de A:
 [-0.37228132  5.37228132]
Vectores propios de A:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [26]:
#Resolución de sistemas de ecuaciones lineales
#AX=BAX = BAX=B:
B = np.array([1, 2])
X = np.linalg.solve(A, B)
print("Solución del sistema AX = B:\n", X)

Solución del sistema AX = B:
 [0.  0.5]


# Indexacion y Slicing

In [27]:
array_1 = np.array([10,20,30,60,12])
print(array_1[1])
print(array_1[-1])

20
12


In [28]:
print(array_1[1:4])

[20 30 60]


In [29]:
print(array_1[1:7])

[20 30 60 12]


In [30]:
print(array_1[-1:-7])

[]


In [32]:
bool_index = array_1 > 25
print(bool_index)
print(type(bool_index))

[False False  True  True False]
<class 'numpy.ndarray'>


In [35]:
index = [2,0,3]
print(array_1[index])

[30 10 60]


In [37]:
#Extraccion de un elemento
array_2 = np.random.randint(1,10,size=(3,3))
print(array_2)
print(array_2[0,1])#fila 0 columna 1

[[7 5 4]
 [1 6 7]
 [2 5 4]]
5


In [42]:
#extraccion por tramos
print(array_2[:1,:1])

[[7]]


# Broadcasting

In [43]:
prices = np.random.randint(100,500, size=(3,3))
discount = np.array([10,20,30])
discount_prices = prices + discount
print(prices)
print(discount_prices)

[[245 287 146]
 [203 427 425]
 [409 261 394]]
[[255 307 176]
 [213 447 455]
 [419 281 424]]


In [44]:
array_3 = np.array([1,2,3,4,5])
print(np.all(array_3 > 0))

True


In [45]:
array_a = np.array([1,2,3])
array_b = np.array([4,5,6])
concatenated_a = np.concatenate((array_a, array_a))
concatenated_ab = np.concatenate((array_a, array_b))
print(concatenated_a)
print(concatenated_ab)

[1 2 3 1 2 3]
[1 2 3 4 5 6]


# Stacking

In [46]:
stacked_v = np.vstack((array_a, array_b))
print(stacked_v)

[[1 2 3]
 [4 5 6]]


In [47]:
stacked_h = np.hstack((array_a, array_b))
print(stacked_h)

[1 2 3 4 5 6]


# Split

In [52]:
array_d = np.arange(1,26)
split_array = np.split(array_d, 5)
print(array_d)
print(split_array)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]), array([11, 12, 13, 14, 15]), array([16, 17, 18, 19, 20]), array([21, 22, 23, 24, 25])]


# Elementos Unicos - Conteos

In [53]:
# Supongamos que tenemos la variable 'respuestas' con las opiniones de los clientes
respuestas = np.array(['bueno', 'excelente', 'malo', 'bueno', 'excelente', 'bueno', 'malo', 'excelente'])

# Utilizamos el método unique para encontrar los elementos únicos
elementos_unicos = np.unique(respuestas)
print(elementos_unicos)


['bueno' 'excelente' 'malo']


In [54]:
# Contar las frecuencias de los elementos únicos
elementos_unicos, conteos = np.unique(respuestas, return_counts=True)
print(elementos_unicos)
print(conteos)

['bueno' 'excelente' 'malo']
[3 3 2]


In [55]:
x = np.arange(10)
vista = x[1:3]

print(x)
print(vista)

# Modificar la vista
x[1:3] = [10, 11]
print(x)
print(vista)

[0 1 2 3 4 5 6 7 8 9]
[1 2]
[ 0 10 11  3  4  5  6  7  8  9]
[10 11]


In [56]:
array_e = np.arange(10)
copy_x = array_e[[1,2]]
print(array_e)
print(copy_x)
array_e[1:3]=[10,11]
print(array_e)
print(copy_x)

[0 1 2 3 4 5 6 7 8 9]
[1 2]
[ 0 10 11  3  4  5  6  7  8  9]
[1 2]


In [57]:
# Crear una copia de la porción del array
copia = x[1:3].copy()

# Hacer cambios en el array original
x[1:3] = [12, 13]
print(x)
print(copia)

[ 0 12 13  3  4  5  6  7  8  9]
[10 11]


# Transpuesta

In [58]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
transposed_matrix = matrix.T
print(matrix)
print(transposed_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


# Reshape

Adecua el orden de los elementos dentro del array

In [60]:
array_f = np.arange(1,13)
reshape_array = array_f.reshape(3,4)
print(array_f)
print(reshape_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## Reverse

In [61]:
reversed_array = array_f[::-1]
print(array_f)
print(reversed_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[12 11 10  9  8  7  6  5  4  3  2  1]


## Flattening

permite convertir una matriz de multiples dimensiones en una matriz de una dimension

permite aplanar la infromacion para que el modelo se pueda entrenar

In [62]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
flattened_array = matrix.flatten()
print(matrix)

print(flattened_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [63]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [64]:
# Suma de matrices
sum = A + B
print(sum)

# Resta de matrices
resta = A - B
print(resta)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


In [65]:
# Producto matricial
producto = np.dot(A, B)
print(producto)

[[19 22]
 [43 50]]


In [66]:
# Determinante
determinante = np.linalg.det(A)
print(determinante)

-2.0000000000000004


In [67]:
# Inversa
inversa = np.linalg.inv(A)
print(inversa)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [68]:
# Resolver sistema de ecuaciones lineales
B = np.array([9, 11])
X = np.linalg.solve(A, B)
print(X)

[-7.  8.]


In [69]:
datos = np.array([23, 76, 35, 67, 89, 45, 68, 79, 35])

media = np.mean(datos)
mediana = np.median(datos)
varianza = np.var(datos)
desviacion = np.std(datos)

print("Media:", media)
print("Mediana:", mediana)
print("Varianza:", varianza)
print("Desviación estándar:", desviacion)

Media: 57.44444444444444
Mediana: 67.0
Varianza: 484.02469135802465
Desviación estándar: 22.000561160071


In [70]:
#Instrucción: Genera un array de 1000 números aleatorios que sigan una distribución normal con media 0 y desviación estándar 1. Calcula la media y desviación estándar del array generado.

datos_simulados = np.random.normal(0, 1, 1000)
media_simulada = np.mean(datos_simulados)
desviacion_simulada = np.std(datos_simulados)

print("Media de los datos simulados:", media_simulada)
print("Desviación estándar de los datos simulados:", desviacion_simulada)

Media de los datos simulados: -0.06601688427335967
Desviación estándar de los datos simulados: 0.9889284895446762
